version: "3.8"

services:
  api:
    build: .
    container_name: fastapi_api
    ports:
      - "8000:8000"
    env_file: .env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - redis
      - postgres

  worker:
    build: .
    container_name: fastapi_worker
    env_file: .env
    command: ["rq", "worker", "default"]
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7-alpine
    container_name: fastapi_redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    container_name: fastapi_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
